#!/bin/sh

# Find all image files in the symlinked wallpapers directory
wallpaper=$(find -L ~/Pictures/wallpapers -type f | wofi --dmenu --prompt 'Pick a wallpaper: ')

# If a wallpaper is selected, set it using swww
if [[ -n "$wallpaper" ]]; then
    swww img "$wallpaper"
else
    echo "No wallpaper selected."
fi

