#!/bin/sh

wallpaper_folder="${HOME}/Pictures/wallpapers"
selected_file=$(shuf -n 1 -e "$wallpaper_folder"/*)
wall="$selected_file"
wal -i "$wall";
pkill swaync;
pkill waybar;
swaync &
waybar &
swww img --transition-type random --transition-fps 60 --transition-duration 2 "$wall"

# swww img --transition-type fade --transition-duration 2 --transition-fps 60 $wall;
# swww img --transition-type grow --transition-pos 0.5,0.5 --transition-fps 60 $wall;

